### PR TITLE
Fix missing discourse_url in README

### LINKED ISSUE #4: Figure out testing off local discourse installation
see 
- https://github.com/discourse/discourse_api#testing
- ...

and don't test against our ropensci install

### PR DESCRIPTION
**Pull request by marionlouveaux**
## Description

- add info for environment variables
- Fix typos in paragraph titles
- add yaml to knit Rmd to md

### CODE REVIEW

**Comment by sckott** [comment]
thanks! super helpful. I should have added that I render the README with knitr, not rmarkdown. can you add a commit with README.md rendered with `knitr::knit('README.Rmd')` or with equivalent rstudio buttons/however you use R.  the yaml header is not needed AFAIK with knitr.  I'll add that bit to the contributing.md file and PR template

**Comment by marionlouveaux** [comment]
You're welcome!
I removed the yaml header.
I added the yaml header, because I didn't know about `knitr::knit('README.Rmd')` and couldn't figure out how to knit the Rmd using the knit button in RStudio without this yaml, and also because it is present in the readme file that is created with `usethis::knit('README.Rmd')`.
Is there an advantage to have a readme without yaml or is it a question of habits?

**Comment by sckott** [comment]
Just habits. By way of an explanation.... I don't use rstudio. I use a text editor (sublime text) and a terminal (iterm). Across all R pkgs I run things like build/install package, knit the readme, run tests, etc. through make commands (using the [Makefile](https://github.com/sckott/discgolf/blob/master/Makefile)) in iterm. And using knitr is just historical since i started making pkgs before rmarkdown was available

**Comment by sckott** [comment]
looks great, thanks!

**Pull request merged**
